version: '3'
services:
  #account services
  accounts_service:
    build:
      context: ./accounts_api
      dockerfile: Dockerfile
    image: accounts_service:latest
    ports:
      - '3001:3000'
    environment:
      DB_HOST: db_accounts
      DB_PORT: 27017
      DB_NAME: auth_db
      JWT_SECRET: mysecretkey
    networks:
      - red_gateway
      - red_micros
      - red_data_layer
    restart: on-failure
  
  #account services database
  db_accounts:
    image: mongo:latest
    volumes:
      - mongodb_accounts:/data/db
    ports:
      - '27018:27017'
    networks:
      - red_data_layer
  
  
  #solicitudes services
  solicitudes_service:
    build:
      context: ./solicitudes_api
      dockerfile: Dockerfile
    image: solicitudes_service:latest
    ports:
      - '3000:3000'
    networks:
      - red_data_layer
      - red_micros
      - red_gateway
    environment:
      DB_HOST: db_solicitudes
      DB_PORT: 27017
      DB_NAME: auth_db
      JWT_SECRET: mysecretkey
    restart: on-failure    
    
  
  
  #solicitud services db
  db_solicitudes:
    image: mongo:latest
    volumes:
      - mongodb_solicitudes:/data/db
    ports:
      - '27017:27017'
    networks:
      - red_data_layer
    restart: on-failure  
  

#ofertas services
  ofertas_service:
    build:
      context: ./ofertas_api
      dockerfile: Dockerfile
    image: ofertas_service:latest
    ports:
      - '3006:3000'
    networks:
      - red_data_layer
      - red_micros
      - red_gateway
    environment:
      DB_HOST: db_ofertas
      DB_PORT: 27018
      DB_NAME: auth_db
      JWT_SECRET: mysecretkey
    restart: on-failure    
    
  
  
  #ofertas services db
  db_ofertas:
    image: mongo:latest
    volumes:
      - mongodb_ofertas:/data/db
    ports:
      - '27019:27017'
    networks:
      - red_data_layer
    restart: on-failure  


  # db admin
  database_admin:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: db_solicitudes
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret
    networks:
      - red_data_layer

 #puerta de enlace       
  nginx:
    image: nginx
    ports:
      - "4488:4488"
    volumes:
      - ./gateway_api/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - red_gateway
    restart: on-failure
    
  
  #message brokuer rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - red_micros
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
  #socket services 
  socket_service:
    image: socket_service:latest
    build:
      context: ./socket_service
      dockerfile: Dockerfile
    ports:
      - '3004:3004'
    networks:
      - red_micros
      - red_gateway
    depends_on:
      - rabbitmq
      - redis_data
    restart: on-failure 
    
  socket_service_replica1:
    image: socket_service:latest
    build:
      context: ./socket_service
      dockerfile: Dockerfile
    ports:
      - '3010:3004'
    networks:
      - red_micros
      - red_gateway
    depends_on:
      - rabbitmq
      - redis_data
    restart: on-failure
    
  

  # #broker message monitor cluster
  # cluster_monitor:
  #   build:
  #     context: ./cluster_service_monitor
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3005:3005'
  #   networks:
  #     - red_micros
  #   healthcheck:
  #     test: ["CMD-SHELL", "nc -z rabbitmq 5672 || exit 1"]
  #     timeout: 30s
  #     retries: 3

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
    volumes:
      - redisinsight-data:/db
    restart: unless-stopped
    networks:
      - red_micros
    environment:
      - REDIS_CONNECTION_HOST=redis
      - REDIS_CONNECTION_PORT=6379

  redis_data:
    image: redis:latest
    #container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - red_micros
#volumenes persistentes
volumes:
  mongodb_accounts:
    driver: local
  mongodb_solicitudes:
    driver: local
  mongodb_ofertas:
    driver: local
  rabbitmq_data:
    driver: local
  redisinsight-data:
  redis_data:


#redes
networks:
  red_micros:
  red_gateway:
  red_data_layer: